doods:
  logger:
    level: warn
  detectors:
    # - name: default
    #   type: tflite
    #   modelFile: models/coco_ssd_mobilenet_v1_1.0_quant.tflite
    #   labelFile: models/coco_labels0.txt
    #   numThreads: 4
    #   numConcurrent: 4
    #   hwAccel: false
    #   timeout: 2m
    # - name: edgetpu
    #   type: tflite
    #   modelFile: models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
    #   labelFile: models/coco_labels0.txt
    #   numThreads: 0
    #   numConcurrent: 4
    #   hwAccel: true
    - name: edgetpu2
      type: tflite
      modelFile: models/ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite
      labelFile: models/coco_labels_v2.txt
      numThreads: 4
      numConcurrent: 4
      hwAccel: true
    - name: mobiledet
      type: tflite
      modelFile: models/ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite
      labelFile: models/coco_labels_mobiledet.txt
      numThreads: 0
      numConcurrent: 4
      hwAccel: true
    # - name: efficientdet
    #   type: tflite
    #   modelFile: models/lite-model_efficientdet_lite0_detection_default_1_edgetpu.tflite
    #   labelFile: models/coco_labels0.txt
    #   numThreads: 0
    #   numConcurrent: 4
    #   hwAccel: true
    # - name: efficientdetuint8
    #   type: tflite
    #   modelFile: models/lite-model_efficientdet_lite0_int8_1_edgetpu.tflite
    #   labelFile: models/coco_labels0.txt
    #   numThreads: 0
    #   numConcurrent: 4
    #   hwAccel: true
    # - name: tensorflow
    #   type: tensorflow
    #   modelFile: models/faster_rcnn_inception_v2_coco_2018_01_28.pb
    #   labelFile: models/coco_labels1.txt
    #   numThreads: 4
    #   numConcurrent: 4
    #   hwAccel: false
    #   timeout: 2m
    # - name: faces
    #   type: tflite
    #   modelFile: models/ssd_mobilenet_v2_face_quant_postprocess_edgetpu.tflite
    #   labelFile: models/coco_labels1.txt
    #   numThreads: 0
    #   numConcurrent: 4
    #   hwAccel: true

    # - name: inceptiontpu
    #   type: tflite
    #   modelFile: models/inception_v4_299_quant_edgetpu.tflite
    #   labelFile: models/imagenet_labels2.txt
    #   # modelFile: models/ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite
    #   # labelFile: models/coco_labels2.txt
    #   numThreads: 0
    #   numConcurrent: 4
    #   hwAccel: true